from ..enums import Neuro, Provider, Category


class NeuroInfo:
    not_working = [Neuro.BENDER,
                   Neuro.VIDEODIFFUSION,
                   Neuro.TENCENTMAKER, 
                   Neuro.GOOGLE, Neuro.LLAMA, 
                   Neuro.MISTRAL, Neuro.SOLAR, 
                   Neuro.OPUS]
    neuros_alph = {
        Provider.FUTUREFORGE: {
            Category.TEXT: [Neuro.GOOGLE, Neuro.LLAMA, 
                            Neuro.MISTRAL, Neuro.SOLAR,
                            Neuro.OPUS],
            Category.IMAGE: [Neuro.VIDEODIFFUSION,
                             Neuro.TENCENTMAKER],
            Category.AUDIO: [Neuro.BENDER],
        },
        Provider.VISIONCRAFT: {
            Category.TEXT: [Neuro.LZLV, Neuro.PYGMALION, 
                            Neuro.AIRBOROS, Neuro.DOLPHIN, Neuro.GEMMA,
                            Neuro.LLAVA, Neuro.GEMINI,
                            Neuro.CHATGPT, Neuro.CLAUDE,
                            Neuro.SONNET, Neuro.HAIKU, Neuro.OPENCHAT,
                            Neuro.STARCODER, Neuro.DBRX, Neuro.MIXTRAL,
                            Neuro.NETGPT, Neuro.WIZARD, Neuro.ZEPHYR],
            Category.IMAGE: [Neuro.GOUFENG, Neuro.ABSOLUTEREALITY, Neuro.AMIREAL,
                             Neuro.ANYTHING,
                             Neuro.ABYSSORANGEMIX, Neuro.BLAZINGDRIVE,
                             Neuro.CETUSMIX,
                             Neuro.COUNTERFEIT, Neuro.CUTEYUKIMIX,
                             Neuro.CYBERREALISTIC,
                             Neuro.DELIBERATE2,
                             Neuro.DREAMSHAPER, Neuro.EOR,
                             Neuro.EIMISANIMEDIFFUSION, Neuro.ELLDRETHS,
                             Neuro.EPICREALISM, Neuro.CANTBELIEVE,
                             Neuro.JUGGERNAUTAFTERMATH, Neuro.LOFI,
                             Neuro.LYRIEL, Neuro.MAJICMIXREALISTIC,
                             Neuro.PASTELMIXSTYLIZED, Neuro.PORTRAITPLUS,
                             Neuro.PROTOGEN, Neuro.REALISTICVISION,
                             Neuro.RUNDIFFUSIONFX, Neuro.SHONINSBEAUTIFUL,
                             Neuro.TIMELESS, Neuro.SDXL, Neuro.JUGGERNAUT,
                             Neuro.ANIMEART,
                             Neuro.T2G,
                             Neuro.DREAMSHAPERXL, Neuro.REALISMENGINE,
                             Neuro.TURBOVISION,
                             Neuro.MEINAHENT, Neuro.LUCIDDREAM,
                             Neuro. CAMELLA, Neuro.KIZUKI, Neuro.DIVINE,
                             Neuro.CREEPY, Neuro.RETROANIME,
                             Neuro.SDXLMIDJOURNEY, Neuro.VOIDMIX,
                             Neuro.ARCHINTER, Neuro.THINKDIFF,
                             Neuro.CYBERTOKYO, Neuro.REALBOY],
        }
    }
